-- Phase 3: Data Model Lock
-- Creates the exact data model for: Trips as source of truth, Upload history, LogEvents

-- ============================================
-- TRIP MODEL UPDATES
-- ============================================
-- Add new fields to Trip model for roster snapshot tracking
ALTER TABLE trip ADD COLUMN "matchKey" TEXT;
ALTER TABLE trip ADD COLUMN "originalRosterSnapshot" TEXT;
ALTER TABLE trip ADD COLUMN "originalSnapshotSetAt" DATETIME;
ALTER TABLE trip ADD COLUMN "currentRosterSnapshot" TEXT;
ALTER TABLE trip ADD COLUMN "currentSnapshotUpdatedAt" DATETIME;
ALTER TABLE trip ADD COLUMN "protectedCreditMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trip ADD COLUMN "currentCreditMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trip ADD COLUMN "payCreditMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trip ADD COLUMN "changeSummary" TEXT;
ALTER TABLE trip ADD COLUMN "changeSeverity" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE trip ADD COLUMN "acknowledgmentRequired" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE trip ADD COLUMN "acknowledgedAt" DATETIME;
ALTER TABLE trip ADD COLUMN "lastUploadId" TEXT;
ALTER TABLE trip ADD COLUMN "premiumEventSuggestions" TEXT;

-- Create index for matchKey
CREATE INDEX "trip_matchKey_idx" ON "trip"("matchKey");
CREATE INDEX "trip_lastUploadId_idx" ON "trip"("lastUploadId");

-- ============================================
-- UPLOAD MODEL (NEW)
-- ============================================
CREATE TABLE "upload" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "imageHash" TEXT,
    "uploadedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "parseResultJson" TEXT NOT NULL DEFAULT '{}',
    "parseConfidence" REAL NOT NULL DEFAULT 0.0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "upload_userId_idx" ON "upload"("userId");
CREATE INDEX "upload_uploadedAt_idx" ON "upload"("uploadedAt");
CREATE INDEX "upload_sourceType_idx" ON "upload"("sourceType");

-- ============================================
-- UPLOAD-TRIP JUNCTION TABLE (Many-to-Many)
-- ============================================
CREATE TABLE "_TripToUpload" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,
    CONSTRAINT "_TripToUpload_A_fkey" FOREIGN KEY ("A") REFERENCES "trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "_TripToUpload_B_fkey" FOREIGN KEY ("B") REFERENCES "upload" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "_TripToUpload_AB_unique" ON "_TripToUpload"("A", "B");
CREATE INDEX "_TripToUpload_B_index" ON "_TripToUpload"("B");

-- ============================================
-- LOG EVENT MODEL (NEW)
-- ============================================
CREATE TABLE "log_event" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "tripId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "premiumCode" TEXT,
    "premiumMinutesDelta" INTEGER,
    "premiumMultiplier" REAL,
    "notes" TEXT,
    "autoGeneratedNotes" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "log_event_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "log_event_userId_idx" ON "log_event"("userId");
CREATE INDEX "log_event_tripId_idx" ON "log_event"("tripId");
CREATE INDEX "log_event_eventType_idx" ON "log_event"("eventType");
CREATE INDEX "log_event_status_idx" ON "log_event"("status");
CREATE INDEX "log_event_createdAt_idx" ON "log_event"("createdAt");

-- ============================================
-- LOG EVENT ATTACHMENT MODEL (NEW)
-- ============================================
CREATE TABLE "log_event_attachment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "logEventId" TEXT NOT NULL,
    "uploadId" TEXT,
    "attachmentUrl" TEXT,
    "attachmentType" TEXT NOT NULL DEFAULT 'image',
    "description" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "log_event_attachment_logEventId_fkey" FOREIGN KEY ("logEventId") REFERENCES "log_event" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "log_event_attachment_uploadId_fkey" FOREIGN KEY ("uploadId") REFERENCES "upload" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX "log_event_attachment_logEventId_idx" ON "log_event_attachment"("logEventId");
CREATE INDEX "log_event_attachment_uploadId_idx" ON "log_event_attachment"("uploadId");
